algo = input('Digite algo: ')
print('Tipo primitivo: ',type(algo))
print('Só tem espaços: ', algo.isspace())
print('É um número: ',algo.isnumeric())
print('É alfanumérico: ',algo.isalnum())
print('É alfabético: ', algo.isalpha())
print('Esta em maiúsculas: ',algo.isupper())
print('Esá em minúsculas: ',algo.islower())
print('Está capitalizada: ',algo.istitle())
print('################################')